# Generated by Django 5.0.4 on 2026-07-10 12:17

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedShow',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RETURNING', 'Returning Series'), ('ENDED', 'Ended'), ('CANCELED', 'Canceled'), ('IN_PRODUCTION', 'In Production')], default='RETURNING', max_length=20)),
                ('vote_average', models.FloatField(default=0.0)),
                ('total_seasons', models.PositiveIntegerField(default=0)),
                ('total_episodes', models.PositiveIntegerField(default=0)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cached_show',
                'indexes': [models.Index(fields=['status'], name='idx_show_status'), models.Index(fields=['last_synced_at'], name='idx_show_last_synced')],
            },
        ),
        migrations.CreateModel(
            name='CachedEpisode',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('season_number', models.PositiveIntegerField()),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('air_date', models.DateField(blank=True, db_index=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(default=0, help_text='Used to increment/decrement UserProfile.total_time_watched on toggle.')),
                ('still_path', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.cachedshow')),
            ],
            options={
                'db_table': 'cached_episode',
                'ordering': ['season_number', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000)),
                ('is_spoiler', models.BooleanField(default=False, help_text='Author-flagged spoiler; hidden behind a reveal tap client-side regardless of watch state.')),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.cachedepisode')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.cachedshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_like',
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('HARASSMENT', 'Harassment or abuse'), ('SPOILER', 'Unmarked spoiler'), ('OFF_TOPIC', 'Off-topic'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('REMOVED', 'Comment removed'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.comment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emotion_emoji', models.CharField(blank=True, choices=[('HAPPY', '😄 Happy'), ('SHOCKED', '😱 Shocked'), ('SAD', '😢 Sad'), ('GOOD', '👍 Good'), ('FUN', '🎉 Fun')], max_length=10)),
                ('mvp_character_id', models.IntegerField(blank=True, help_text='TMDB credit/person id of the voted MVP character.', null=True)),
                ('mvp_character_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(db_column='episode_id', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.cachedepisode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'episode_interaction',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(blank=True, help_text="Public URL to the user's avatar image.", max_length=500, null=True)),
                ('total_time_watched', models.PositiveIntegerField(default=0, help_text='Cumulative minutes watched, derived from summed episode runtimes.')),
                ('earned_badges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text="Slugs of unlocked milestone badges, e.g. 'binge_master', 'anime_fan'.", size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TO_WATCH', 'To Watch'), ('UP_TO_DATE', 'Up To Date'), ('ARCHIVED', 'Archived')], default='TO_WATCH', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='core.cachedshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist',
            },
        ),
        migrations.CreateModel(
            name='WatchState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(db_column='episode_id', on_delete=django.db.models.deletion.CASCADE, related_name='watch_states', to='core.cachedepisode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watch_state',
            },
        ),
        migrations.CreateModel(
            name='WatchStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Number of consecutive calendar days with at least one watched episode.')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='All-time record for consecutive days watched.')),
                ('total_streak_days', models.PositiveIntegerField(default=0, help_text='Total number of distinct calendar days on which at least one episode was watched.')),
                ('last_watch_date', models.DateField(blank=True, help_text='Calendar date (UTC) of the most recent episode watch.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watch_streak',
            },
        ),
        migrations.AddIndex(
            model_name='cachedepisode',
            index=models.Index(fields=['show', 'season_number'], name='idx_episode_show_season'),
        ),
        migrations.AddIndex(
            model_name='cachedepisode',
            index=models.Index(fields=['air_date'], name='idx_episode_air_date'),
        ),
        migrations.AddConstraint(
            model_name='cachedepisode',
            constraint=models.UniqueConstraint(fields=('show', 'season_number', 'episode_number'), name='unique_show_season_episode'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['show', 'parent', '-created_at'], name='idx_comment_show_feed'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['episode', 'parent', '-created_at'], name='idx_comment_episode_feed'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='idx_comment_replies'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='idx_comment_user'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('episode__isnull', True), ('show__isnull', False)), models.Q(('episode__isnull', False), ('show__isnull', True)), _connector='OR'), name='comment_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment'], name='idx_commentlike_comment'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_comment_like'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['status', '-created_at'], name='idx_report_status_created'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['comment'], name='idx_report_comment'),
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'comment'), name='unique_reporter_comment_report'),
        ),
        migrations.AddIndex(
            model_name='episodeinteraction',
            index=models.Index(fields=['user', 'episode'], name='idx_interaction_user_episode'),
        ),
        migrations.AddConstraint(
            model_name='episodeinteraction',
            constraint=models.UniqueConstraint(fields=('user', 'episode'), name='unique_user_episode_interaction'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['total_time_watched'], name='idx_profile_time_watched'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'status'], name='idx_watchlist_user_status'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'show'), name='unique_user_show_watchlist'),
        ),
        migrations.AddIndex(
            model_name='watchstate',
            index=models.Index(fields=['user', 'episode'], name='idx_watchstate_user_episode'),
        ),
        migrations.AddIndex(
            model_name='watchstate',
            index=models.Index(fields=['user', 'watched_at'], name='idx_watchstate_user_watched_at'),
        ),
        migrations.AddConstraint(
            model_name='watchstate',
            constraint=models.UniqueConstraint(fields=('user', 'episode'), name='unique_user_episode_id'),
        ),
    ]
