# Generated by Django 6.0.7 on 2026-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_movie_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="ignore_catchup",
            field=models.BooleanField(
                default=False,
                help_text="If true, skip the 'mark previous episodes watched?' Catch-Up modal for this show — always behave as if the user chose 'just this one'. Set via 'Never for this show' in the modal.",
            ),
        ),
    ]
