# Generated by Django 6.0.7 on 2026-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_watchlist_ignore_catchup"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedshow",
            name="next_episode_air_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedshow",
            name="next_episode_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cachedshow",
            name="next_episode_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedshow",
            name="next_episode_season_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
