# Generated by Django 6.0.7 on 2026-07-15 19:04

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cachedshow_next_episode_air_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviewatchstate',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='watchstate',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Normalised export, staged here rather than passed as a Celery argument — a full series export is ~3MB and the broker is the wrong place to put it. Cleared once the run finishes.')),
                ('total', models.PositiveIntegerField(default=0, help_text='Shows + movies to process. Denominator for progress.')),
                ('processed', models.PositiveIntegerField(default=0, help_text='Shows + movies resolved so far (succeeded or not).')),
                ('shows_imported', models.PositiveIntegerField(default=0)),
                ('shows_skipped', models.PositiveIntegerField(default=0)),
                ('movies_imported', models.PositiveIntegerField(default=0)),
                ('movies_skipped', models.PositiveIntegerField(default=0)),
                ('episodes_marked', models.PositiveIntegerField(default=0, help_text='WatchState rows created. The number users actually care about.')),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('detail', models.TextField(blank=True, help_text='Failure reason when status=FAILED.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_job',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_import_job_user')],
            },
        ),
    ]
