# Generated by Django 6.0.7 on 2026-07-16 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_moviewatchstate_watched_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], max_length=16)),
                ('provider_user_id', models.CharField(help_text="Stable 'sub' claim from the provider's ID token.", max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email asserted by the provider at link time (may be an Apple private-relay address).', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_account',
                'indexes': [models.Index(fields=['user', 'provider'], name='idx_social_user_provider')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uniq_social_provider_identity')],
            },
        ),
    ]
