# Generated by Django 6.0.7 on 2026-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_socialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedshow",
            name="original_language",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="moviecache",
            name="original_language",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
