# Generated by Django 6.0.7 on 2026-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_original_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Touched on every progress save. Lets a stuck/orphaned RUNNING row (worker died mid-import) be told apart from one that's genuinely still working."),
        ),
    ]
