# Generated by Django 6.0.7 on 2026-07-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_importjob_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Normalised export, staged here rather than passed as a Celery argument — a full series export is ~3MB and the broker is the wrong place to put it. Cleared once the run SUCCEEDS; kept on FAILED (alongside `processed`) so TVTimeImportView can resume a byte-identical resubmission instead of restarting from zero.",
            ),
        ),
    ]
