# Generated by Django 6.0.7 on 2026-07-29 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_moviereview_showreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=280)),
                ("is_private", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_list",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("tv", "TV Show"), ("movie", "Movie")], max_length=5
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.customlist",
                    ),
                ),
            ],
            options={
                "db_table": "custom_list_item",
                "ordering": ["-added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customlist",
            index=models.Index(
                fields=["user", "-updated_at"], name="idx_customlist_user_updated"
            ),
        ),
        migrations.AddIndex(
            model_name="customlistitem",
            index=models.Index(fields=["list"], name="idx_customlistitem_list"),
        ),
        migrations.AddIndex(
            model_name="customlistitem",
            index=models.Index(
                fields=["media_type", "tmdb_id"], name="idx_customlistitem_media_tmdb"
            ),
        ),
        migrations.AddConstraint(
            model_name="customlistitem",
            constraint=models.UniqueConstraint(
                fields=("list", "media_type", "tmdb_id"), name="unique_list_media_tmdb"
            ),
        ),
    ]
