# Generated by Django 6.0.7 on 2026-07-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_customlist_customlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="payload_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="sha256 of the sorted payload, computed once at job creation. TVTimeImportView compares a resubmission's fingerprint against this instead of re-fetching and deep-comparing a multi-MB `payload` JSONField on every retry — the same resume check for a fraction of the CPU/DB cost, which matters on a free-tier single-worker box under exactly the retry traffic (a user hitting 'try again' after a failed import) this exists to help.",
                max_length=64,
            ),
        ),
    ]
