# Generated by Django 6.0.7 on 2026-07-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_importjob_payload_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedepisode",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedshow",
            name="airs_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedshow",
            name="airs_timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="cachedshow",
            name="airtime_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
