# Generated by Django 6.0.7 on 2026-08-01 13:43

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_cachedepisode_notified_at_cachedshow_airs_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereview",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.5")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="showreview",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.5")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="moviereview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rating__in",
                        [
                            Decimal("0.5"),
                            Decimal("1.0"),
                            Decimal("1.5"),
                            Decimal("2.0"),
                            Decimal("2.5"),
                            Decimal("3.0"),
                            Decimal("3.5"),
                            Decimal("4.0"),
                            Decimal("4.5"),
                            Decimal("5.0"),
                        ],
                    )
                ),
                name="movie_review_rating_half_steps",
            ),
        ),
        migrations.AddConstraint(
            model_name="showreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rating__in",
                        [
                            Decimal("0.5"),
                            Decimal("1.0"),
                            Decimal("1.5"),
                            Decimal("2.0"),
                            Decimal("2.5"),
                            Decimal("3.0"),
                            Decimal("3.5"),
                            Decimal("4.0"),
                            Decimal("4.5"),
                            Decimal("5.0"),
                        ],
                    )
                ),
                name="show_review_rating_half_steps",
            ),
        ),
    ]
