# Generated by Django 6.0.7 on 2026-08-01 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_moviereview_rating_alter_showreview_rating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Ghost mode: excluded from user search, activity feed, and public profile.",
            ),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "follow",
                "indexes": [
                    models.Index(
                        fields=["follower", "-created_at"],
                        name="idx_follow_follower_created",
                    ),
                    models.Index(
                        fields=["following", "-created_at"],
                        name="idx_follow_following_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "following"),
                        name="unique_follower_following",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("following")), _negated=True
                        ),
                        name="follow_not_self",
                    ),
                ],
            },
        ),
    ]
