# Generated by Django 6.0.7 on 2026-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_userprofile_is_private_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedepisode",
            name="air_datetime",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedshow",
            name="next_episode_air_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedshow",
            name="tvmaze_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
