# Generated by Django 6.0.7 on 2026-08-03 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_air_time_truth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="total_rewatch_time_watched",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cumulative minutes watched via a rewatch — a subset already included in total_time_watched.",
            ),
        ),
        migrations.CreateModel(
            name="ShowRewatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewatches",
                        to="core.cachedshow",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_rewatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "show_rewatch",
            },
        ),
        migrations.CreateModel(
            name="RewatchEpisodeState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("watched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewatch_states",
                        to="core.cachedepisode",
                    ),
                ),
                (
                    "rewatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_states",
                        to="core.showrewatch",
                    ),
                ),
            ],
            options={
                "db_table": "rewatch_episode_state",
            },
        ),
        migrations.CreateModel(
            name="MovieRewatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("watched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewatches",
                        to="core.moviecache",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_rewatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "movie_rewatch",
                "indexes": [
                    models.Index(
                        fields=["user", "movie"], name="idx_movierewatch_user_movie"
                    ),
                    models.Index(
                        fields=["user", "watched_at"], name="idx_movierewatch_user_time"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="showrewatch",
            index=models.Index(
                fields=["user", "show", "completed_at"],
                name="idx_rewatch_user_show_done",
            ),
        ),
        migrations.AddConstraint(
            model_name="showrewatch",
            constraint=models.UniqueConstraint(
                fields=("user", "show", "round_number"), name="unique_user_show_round"
            ),
        ),
        migrations.AddIndex(
            model_name="rewatchepisodestate",
            index=models.Index(
                fields=["rewatch", "episode"], name="idx_rewatch_state_rewatch_ep"
            ),
        ),
        migrations.AddConstraint(
            model_name="rewatchepisodestate",
            constraint=models.UniqueConstraint(
                fields=("rewatch", "episode"), name="unique_rewatch_episode"
            ),
        ),
    ]
