# Generated by Django 6.0.7 on 2026-08-05 08:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rewatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedepisode',
            name='air_datetime_estimated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cachedshow',
            name='air_time_source',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='cachedshow',
            name='networks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list),
        ),
    ]
